---
language: go
before_install:
- env | awk '/SSH_AUTH_SOCK/ { print "export " $0 }' > ~/.ssh/agent.out
- gvm version
- echo running gvm install twice is important.
- gvm install go1.1 || true
- gvm install go1.1 || true
- gvm use go1.1
- export GOPATH="$HOME/gopath:$GOPATH"
- source ~/.ssh/agent.out
install: cd $TRAVIS_BUILD_DIR && make build
script: cd $TRAVIS_BUILD_DIR && make test
notifications:
  email:
    recipients:
      - flintknappers+sqlutil@modcloth.com
